# config/meta.yml

meta_product_name: "Care Bridge"
meta_title: "Care Bridge - Care for the loved ones that cared for you."
meta_description: "At Care Bridge we understand that you worried that you are worried about those far away.  We make complex tasks easy, for your loved ones."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
